import { pgTable, uuid, text, timestamp } from 'drizzle-orm/pg-core'

// Convention: snake_case column names; uuid primary keys generated by the database.
export const users = pgTable('users', {
  id:         uuid('id').primaryKey().defaultRandom(),
  externalId: text('external_id').notNull().unique(), // Azure AD B2C sub claim
  email:      text('email'),
  createdAt:  timestamp('created_at').defaultNow().notNull(),
})

// push-notifications addon
export const deviceTokens = pgTable('device_tokens', {
  id:        uuid('id').primaryKey().defaultRandom(),
  userId:    text('user_id').notNull(),               // references users.external_id
  token:     text('token').notNull().unique(),         // ANH registration token
  platform:  text('platform').notNull(),               // 'apns' | 'gcm'
  createdAt: timestamp('created_at').defaultNow().notNull(),
})
